### ISSUE TITLE
error: jk-aur: signature from "JustKidding <jk@vin.ovh>" is unknown trust

### ISSUE THREAD

**Issue by quite** [jstkdng/aur#1]
A new key?

**Comment by jstkdng** [comment]
I think my old key was due to expire soon. Just update the old key

**Comment by gabrielkulp** [comment]
Where can I find the new key? I must've found the URL and key at some point since they're in my pacman.conf, but I can't find that info again. Might I suggest you add instructions to this repo's README?

**Comment by jstkdng** [comment]
The fingerprint is the same. I just renewd the expiration.
The fingerprint is in the README.

**Comment by gabrielkulp** [comment]
I don't see a fingerprint in the README [here](https://github.com/jstkdng/aur) or [here](https://github.com/jstkdng/ungoogled-chromium). What am I missing?

**Comment by jstkdng** [comment]
hmmm, the README with the instructions is in the obs branch of this repository. Forgot to update the master branch's README.

**Comment by Master0ne** [comment]
```
$ sudo pacman-key -r 3DEA62513C8035383A245A12E5786B42E8E5D565
gpg: keyserver receive failed: General error
==> ERROR: Remote key not fetched correctly from keyserver.
```

**Comment by gabrielkulp** [comment]
```
$ sudo pacman-key -r 3DEA62513C8035383A245A12E5786B42E8E5D565
gpg: key E5786B42E8E5D565: "JustKidding <jk@vin.ovh>" 6 new signatures
gpg: Total number processed: 1
gpg:         new signatures: 6
```

That command worked for me. All fixed now!

**Comment by Master0ne** [comment]
> That command worked for me. All fixed now!

That's odd, still doesn't work for me. Which key server are you using?

````
$ cat .gnupg/gpg.conf
#keyserver hkps://keys.openpgp.org
#keyserver hkp://pgp.mit.edu:11371
keyserver hkp://pool.sks-keyservers.net
keyserver ldap://keyserver.pgp.com
keyserver hkp://keys.openpgp.org
````

**Comment by gabrielkulp** [comment]
I don't have a `~/.gnupg/gpg.conf`, so this is probably default:
```
$ cat /etc/pacman.d/gnupg/gpg.conf 
no-greeting
no-permission-warning
lock-never
keyserver hkp://pool.sks-keyservers.net
keyserver-options timeout=10
keyserver-options import-clean
keyserver-options no-self-sigs-only
```

**Comment by quite** [comment]
Given that SKS keyservers' network is broken by abuse, the defaults are not
great. I follow the advice in https://gist.github.com/rjhansen/67ab921ffb4084c865b3618d6955275f -- *only*
`keyserver hkps://keys.openpgp.org`, *only* in `dirmngr.conf`. If a key is
not present on that server, one will have to find another reliable source of
publication (hopefully). @jstkdng could maintain their key on
https://keys.openpgp.org/ :)

**Comment by jstkdng** [comment]
Alright. Just uploaded my key to keys.openpgp.org
![image](https://user-images.githubusercontent.com/52050345/89704252-e0f74c80-d917-11ea-93f7-7e24d0a990c8.png)
Will move the documentation to the master branch as soon as I can. Closing.

**Comment by coxackie** [comment]
Also getting
```
$ sudo pacman-key -r 3DEA62513C8035383A245A12E5786B42E8E5D565
gpg: keyserver receive failed: General error
==> ERROR: Remote key not fetched correctly from keyserver.
```
What am I doing wrong? Instructions are not so great. Can you please help?

Update: I also checked `https://keys.openpgp.org/`; it does find the key (with `--search-keys`), but cannot receive it: 
```
gpg --keyserver https://keys.openpgp.org/ --recv-keys 3DEA62513C8035383A245A12E5786B42E8E5D565
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```

**Comment by jstkdng** [comment]
@coxackie 
The correct command is
`gpg --keyserver hkps://keys.openpgp.org/ --recv-keys 3DEA62513C8035383A245A12E5786B42E8E5D565`
I'll add that to the readme

**Comment by coxackie** [comment]
@jstkdng ok, this helped a bit, but still there is problem afterwards (I was pressing "Y" to the key imports below):
```
sudo pacman -Sy
error: jk-aur: key "4490FF6B512EDCB78A69323F92BA500565FD1CB0" is unknown
:: Import PGP key 4490FF6B512EDCB78A69323F92BA500565FD1CB0? [Y/n] 
error: key "4490FF6B512EDCB78A69323F92BA500565FD1CB0" could not be looked up remotely
:: Synchronising package databases...
 core is up to date
 extra is up to date
 community is up to date
 jk-aur                                       13.2 KiB  0.00   B/s 00:00 [----------------------------------------] 100%
 jk-aur.sig                                  566.0   B  0.00   B/s 00:00 [----------------------------------------] 100%
error: jk-aur: key "4490FF6B512EDCB78A69323F92BA500565FD1CB0" is unknown
:: Import PGP key 4490FF6B512EDCB78A69323F92BA500565FD1CB0? [Y/n] 
error: key "4490FF6B512EDCB78A69323F92BA500565FD1CB0" could not be looked up remotely
error: failed to update jk-aur (invalid or corrupted database (PGP signature))
error: failed to synchronize all databases
```

**Comment by jstkdng** [comment]
@coxackie 
I updated the README yesterday, go check it out.

**Comment by bennyhillthebest** [comment]
getting this error again. Is the key expired?
